In [319]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [320]:
x = torch.tensor([[-0.7411, -0.5078,-0.3206], 
                       [0.0983, -0.0308, -0.3728],
                       [0.0414,0.2323,-0.2365],
                       [-0.7342,0.4264,2.0237]],
                     requires_grad=True)


print(x)

tensor([[-0.7411, -0.5078, -0.3206],
        [ 0.0983, -0.0308, -0.3728],
        [ 0.0414,  0.2323, -0.2365],
        [-0.7342,  0.4264,  2.0237]], requires_grad=True)


In [321]:
y = torch.FloatTensor([[0.00,1.00,0.00],[1.00,0.00,0.00],
                 [0.00,1.00,0.00],[0.00,0.00,1.00]],)
print(y)

tensor([[0., 1., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [334]:
#### Creatig Module
class NeuralNetwork(nn.Module):
    def __init__(self):
        w1 = [[1.6035, -1.5062,0.2761], [1.2347, -0.4446, -0.2612], 
              [-0.2296,-0.1559,-0.4434]]
        b1 = [0.3919,-1.2507,-0.9480]
        w2 = [[0.0125,1.2424,0.3503],[-3.0292,-1.0667,-0.0290],
              [-0.457,0.9337,0.1825]]
        b2 = [-1.5651,-0.0845,1.6039]
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(3,3)
        self.fc2 = nn.Linear(3,3)
        self.fc1.bias = nn.Parameter(torch.FloatTensor(b1))
        self.fc1.weight = nn.Parameter(torch.FloatTensor(w1))
        self.fc2.weight = nn.Parameter(torch.FloatTensor(w2))
        self.fc2.bias = nn.Parameter(torch.FloatTensor(b2))
        
    def forward(self,x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [335]:
####Instantiate the NeuralNetwork
model = NeuralNetwork()
print(model.fc1.weight)
print(model.fc2.weight)
print("-------------")
print(model.fc1.bias)
print(model.fc2.bias)

Parameter containing:
tensor([[ 1.6035, -1.5062,  0.2761],
        [ 1.2347, -0.4446, -0.2612],
        [-0.2296, -0.1559, -0.4434]], requires_grad=True)
Parameter containing:
tensor([[ 0.0125,  1.2424,  0.3503],
        [-3.0292, -1.0667, -0.0290],
        [-0.4570,  0.9337,  0.1825]], requires_grad=True)
-------------
Parameter containing:
tensor([ 0.3919, -1.2507, -0.9480], requires_grad=True)
Parameter containing:
tensor([-1.5651, -0.0845,  1.6039], requires_grad=True)


In [336]:
model.parameters

<bound method Module.parameters of NeuralNetwork(
  (fc1): Linear(in_features=3, out_features=3, bias=True)
  (fc2): Linear(in_features=3, out_features=3, bias=True)
)>

In [337]:
####Backward Propagation， Define the loss function and optimizer
loss_function = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(),lr = 0.01)

In [338]:
epochs = 20
final_loss = []
for i in range(epochs):
    i = i+1
    y_pred = model.forward(x)
    print("---------")
    print(y_pred)
    loss = loss_function(y_pred,y)
    final_loss.append(loss)
    print("Epoch number:{}".format(i))
    print("----------WEIGHT---------")
    print(model.fc1.weight)
    print(model.fc2.weight)
    print("----------BIAS-----------")
    print(model.fc1.bias)
    print(model.fc2.bias)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print("----------LOSS----------")
    print(f"epoch = {i}, loss = {loss}")

---------
tensor([[-1.5651, -0.0845,  1.6039],
        [-1.5589, -1.5778,  1.3786],
        [-1.5646, -0.2150,  1.5842],
        [-1.5651, -0.0845,  1.6039]], grad_fn=<AddmmBackward0>)
Epoch number:1
----------WEIGHT---------
Parameter containing:
tensor([[ 1.6035, -1.5062,  0.2761],
        [ 1.2347, -0.4446, -0.2612],
        [-0.2296, -0.1559, -0.4434]], requires_grad=True)
Parameter containing:
tensor([[ 0.0125,  1.2424,  0.3503],
        [-3.0292, -1.0667, -0.0290],
        [-0.4570,  0.9337,  0.1825]], requires_grad=True)
----------BIAS-----------
Parameter containing:
tensor([ 0.3919, -1.2507, -0.9480], requires_grad=True)
Parameter containing:
tensor([-1.5651, -0.0845,  1.6039], requires_grad=True)
----------LOSS----------
epoch = 1, loss = 1.7807989120483398
---------
tensor([[-1.5630, -0.0807,  1.5980],
        [-1.5563, -1.5606,  1.3741],
        [-1.5625, -0.1971,  1.5804],
        [-1.5630, -0.0807,  1.5980]], grad_fn=<AddmmBackward0>)
Epoch number:2
----------WEIGHT------

In [ ]:
####backup
w1 = [[-1.6035, 1.5062,0.2761], [1.2347, -0.4446, -0.2612], [-0.2296,-0.1559,-0.4434]]
b1 = [0.3919,-1.2507,-0.9480]
w2 = [[0.0125,1.2424,0.3503],[-3.0292,-1.0667,-0.0290],[-0.457,0.9337,0.1825]]
b2 = [-1.5651,-0.0845,1.6039]
print(model.fc1.weight)
print(model.fc1.bias)
model.fc1.weight = nn.Parameter(torch.FloatTensor(w1))
model.fc1.bias = nn.Parameter(torch.tensor(b1))
print(model.fc1.weight)
print(model.fc1.bias)
print("---------------------")
model.fc2.weight = nn.Parameter(torch.tensor(w2))
model.fc2.bias = nn.Parameter(torch.tensor(b2))
print(model.fc2.weight)
print(model.fc2.bias)

In [232]:
loss = nn.BCELoss()
target = [[0.00,1.00,0.00]]
target1 = torch.FloatTensor(tt)
input = torch.tensor(target,requires_grad=True) 
output = loss(input, target1)
print(input)
print("-----OUTPUT-------")
print(output)
output.backward()

tensor([[0., 1., 0.]], requires_grad=True)
-----OUTPUT-------
tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward0>)


In [327]:
import numpy as num
import torch
y_pred = num.array([0.1582, 0.4139, 0.2287])
y_true = num.array([0.0, 1.0, 0.0]) 

####self defined cross entropy
def CrossEntropy(y_pred, y_true):
    total_bce_loss = num.sum(-y_true * num.log(y_pred))
    return total_bce_loss
crossentropy_value = CrossEntropy(y_pred, y_true)
print ("CE loss is: " + str(crossentropy_value))
print("--------------")

#####defualt crossentropyloss
crossentropy_loss = torch.nn.BCELoss()
input = torch.tensor(y_pred)
target11 = torch.tensor(y_true)
output = crossentropy_loss(input, target11)
print("CE loss is: {}".format(output))

CE loss is: 0.8821308802274503
--------------
CE loss is: 0.4380071929717669


In [ ]:
target = torch.tensor([1,0,1,2],dtype=torch.long)

In [266]:
m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss()
# input is of size N x C = 3 x 5
input = torch.randn(3, 5, requires_grad=True)
# each element in target has to have 0 <= value < C
target = torch.tensor([1, 0, 4])
output = loss(m(input), target)
output.backward()